language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode7.2
      brew_packages: cairo
      latex: false
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true
      latex: false

before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty main" -y
  - sudo apt-get update -q
  - sudo apt-get install --only-upgrade libcairo2
  - sudo apt-get install libcairo2-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
